Node/src/main/java/de/iai/ilcd/security/UserAccessBean.java
package de.iai.ilcd.security;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;

import de.iai.ilcd.model.common.DataSet;
import de.iai.ilcd.model.dao.UserDao;
import de.iai.ilcd.model.security.User;
import de.iai.ilcd.webgui.controller.AbstractHandler;

/**
 * User access bean
 */
@ManagedBean( name = "user" )
@ViewScoped
public class UserAccessBean extends AbstractHandler {

	/**
	 * Serialization ID
	 */
	private static final long serialVersionUID = 556220221006512832L;

	/**
	 * User object
	 */
	private User user = null;

	/**
	 * Determine if user is logged in
	 * 
	 * @return <code>true</code> if user logged in, else <code>false</code>
	 */
	public boolean isLoggedIn() {
		Subject currentUser = SecurityUtils.getSubject();
		if ( currentUser == null ) {
			return false;
		}

		if ( currentUser.isAuthenticated() ) {
			return true;
		}
		else {
			return false;
		}
	}

	/**
	 * Determine if user shall be able to enter admin area
	 * 
	 * @return <code>true</code> if access shall be granted, <code>false</code> otherwise
	 * @see SecurityUtil#hasAdminAreaAccessRight()
	 */
	public boolean hasAdminAreaAccessRight() {
		return SecurityUtil.hasAdminAreaAccessRight();
	}

	/**
	 * Determine if user is super admin
	 * 
	 * @return <code>true</code> if super admin access shall be granted, <code>false</code> otherwise
	 * @see SecurityUtil#hasSuperAdminPermission()
	 */
	public boolean hasSuperAdminPermission() {
		return SecurityUtil.hasSuperAdminPermission();
	}

	/**
	 * Determine if the current user has dataset detail view (means {@link ProtectionType#EXPORT}) right
	 * 
	 * @param ds
	 *            data set to check for
	 * @return <code>true</code> if dataset detail view right is present, <code>false</code> otherwise
	 */
	public boolean hasDatasetDetailRights( DataSet ds ) {
		return SecurityUtil.hasExportPermission( ds );
	}

	/**
	 * Get the user name of the current user
	 * 
	 * @return user name of the current user
	 */
	public String getUserName() {
		Subject currentUser = SecurityUtils.getSubject();
		if ( currentUser == null ) {
			return null;
		}
		else {
			return (String) currentUser.getPrincipal();
		}
	}

	/**
	 * Get the user object for the current user.
	 * 
	 * @return user object
	 */
	public User getUserObject() {
		if ( this.user == null ) {
			String userName = this.getUserName();
			if ( userName != null ) {
				UserDao uDao = new UserDao();
				User u = uDao.getUser( userName );
				if ( u != null ) {
					this.user = u;
				}
			}
		}
		return this.user;

	}

}

Node/src/main/webapp/templates/default/design.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html" locale="#{localeBean.locale}">
        <h:head>
            <title>#{pageTitle} - #{conf.applicationTitle}</title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <meta http-equiv="Content-Language" content="en" />
            <meta name="Keywords" content="list of keywords" />
            <meta name="Description" content="description text" />

            <!-- Following file used for menu highlight hover event binding -->
            <script src="#{conf.contextPath}#{conf.templatePath}/scripts/default.js" type="text/javascript"></script>
            
            <link type="text/css" rel="stylesheet" href="#{conf.contextPath}#{conf.templatePath}/css/site.css" media="all" />
        </h:head>
    
        <h:body>
            <div class="minMax">
                <div class="ui-helper-hidden-accessible" title="Accessibility tools">
                    <ul>
                        <li><a href="#content" accesskey="S">#{i18n['public.accessibility.main']}</a></li>
                        <li><a href="#container">#{i18n['public.accessibility.naviMenu']}</a></li>
                    </ul>
                </div>
    
                <div class="header ui-widget-header ui-corner-all">
                    <h:graphicImage rendered="#{conf.logoProvided}" value="#{conf.logoPath}" alt="#{conf.applicationTitle}" />
                    <a href="#{conf.contextPath}/">#{conf.applicationTitle}</a>
					<ui:fragment rendered="#{availableStocks.allStocksMeta.size() > 1}">
						<div class="floatRight">
							<h:form>
								<h:panelGrid columns="2">
									<p:outputLabel value="#{i18n['common.stock.selected']}:" for="selectDataStock" />
									<p:selectOneMenu id="selectDataStock" value="#{stockSelection.currentStockName}" valueChangeListener="#{stockSelection.stockChangeEventHandler}">
										<f:selectItems value="#{availableStocks.allStocksMeta}" var="stock" itemLabel="#{stock.name}" itemValue="#{stock.name}" />
										<f:ajax listener="#{stockSelection.navigate}" />
									</p:selectOneMenu>
								</h:panelGrid>
							</h:form>
						</div>
					</ui:fragment>
					<ui:fragment rendered="#{not empty stockSelection.currentStock}">
					<div class="clearRight selectedDataStock">#{i18n['common.stock']}: #{empty stockSelection.currentStock.longTitleValue ? stockSelection.currentStock.name : stockSelection.currentStock.longTitleValue}</div>
					</ui:fragment>
                </div>
    
                <div>
                    <ui:insert name="contentBody" />
                </div>
    
                <div class="footer ui-widget-header ui-corner-all">
                   <div id="rightFooter">soda4LCA #{conf.appVersion}</div>
                    <div id="leftFooter">
                        <h:panelGroup rendered="#{user.loggedIn}">
                            <h:link outcome="#{url.user.profile}" value="#{i18n['common.profile']}" />
                            |
                            <h:link outcome="#{url.user.password}" value="#{i18n['common.password']}" />
                            |
                            <h:link outcome="#{url.user.logout}" value="#{i18n['public.user.logout']}" />
                            <h:outputText value=" (#{i18n['admin.user']}: #{user.userName})" />
                        </h:panelGroup>
                        <h:panelGroup rendered="#{not user.loggedIn}">
                            <h:link rendered="#{conf.registrationActivated}" outcome="#{url.user.registration}" value="#{i18n['public.user.register']}" />
                            <h:outputText rendered="#{conf.registrationActivated}" value=" | " />
                            <h:link outcome="#{url.user.login}" value="#{i18n['public.user.login']}" rendered="#{conf.displayConfig.showLoginLink}"/>
                        </h:panelGroup>
                    </div>
                </div>
            </div>
        </h:body>
    </f:view>
</html>

Node/src/main/webapp/templates/default/frontend.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:pe="http://primefaces.org/ui/extensions">

    <h:body>
        <ui:composition template="#{conf.templatePath}/design.xhtml">
            <ui:define name="contentBody">
                <pe:importConstants className="de.iai.ilcd.util.SodaUtil" var="Constants" />
                <pe:importEnum type="de.iai.ilcd.model.common.DataSetType" var="DataSetType" />
                <div id="container">
                    <div id="leftColumn">
                        <ui:include src="#{conf.templatePath}/leftMenu.xhtml" />
                    </div>
                    <div id="rightColumn" style="margin-left: 220px; margin-right: 2%">

                        <div id="content">
                            <h1>#{pageTitle}</h1>
                            <div class="story">
                                <h:panelGroup rendered="#{not empty pageSubTitle}">
                                    <h2>#{pageSubTitle}</h2>
                                </h:panelGroup>
                                <ui:insert name="content">Content</ui:insert>
                            </div>
                        </div>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

Node/src/main/webapp/templates/default/leftMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form>
		<p:menu id="mainmenu_container">
 			<p:menuitem value="#{i18n['public.home']}" styleClass="#{activeMenu == Constants.MENU_HOME ? 'ui-state-active' : ''}" url="#{url.index}" />
			<p:menuitem rendered="#{user.hasAdminAreaAccessRight()}" value="#{i18n['admin.adminArea']}" url="#{url.adminIndex}" />
	        <p:submenu label="#{i18n['public.browseDatasets']}">
	            <p:menuitem value="#{i18n['common.processes']}" rendered="#{feature.browseProcesses}" styleClass="#{activeMenu == Constants.MENU_PROCESS ? 'ui-state-active' : ''}" url="#{url.process.list}" />
	            <p:menuitem value="#{i18n['common.lciaMethods']}" rendered="#{feature.browseLCIAMethods}" styleClass="#{activeMenu == Constants.MENU_LCIAMETHOD ? 'ui-state-active' : ''}" url="#{url.lciaMethod.list}" />
	            <p:menuitem value="#{i18n['common.elementaryFlows']}" rendered="#{feature.browseFlows}" styleClass="#{activeMenu == Constants.MENU_ELEMENTARY_FLOW ? 'ui-state-active' : ''}" url="#{url.eflow.list}" />
	            <p:menuitem value="#{i18n['common.productFlows']}" rendered="#{feature.browseFlows}" styleClass="#{activeMenu == Constants.MENU_PRODUCT_FLOW ? 'ui-state-active' : ''}" url="#{url.pflow.list}" />
	            <p:menuitem value="#{i18n['common.flowProperties']}" rendered="#{feature.browseFlowProperties}" styleClass="#{activeMenu == Constants.MENU_FLOWPROPERTY ? 'ui-state-active' : ''}" url="#{url.flowProperty.list}" />
	            <p:menuitem value="#{i18n['common.unitGroups']}" rendered="#{feature.browseUnitGroups}" styleClass="#{activeMenu == Constants.MENU_UNITGROUP ? 'ui-state-active' : ''}" url="#{url.unitGroup.list}" />
	            <p:menuitem value="#{i18n['common.sources']}" rendered="#{feature.browseSources}" styleClass="#{activeMenu == Constants.MENU_SOURCE ? 'ui-state-active' : ''}" url="#{url.source.list}" />
	            <p:menuitem value="#{i18n['common.contacts']}" rendered="#{feature.browseContacts}" styleClass="#{activeMenu == Constants.MENU_CONTACT ? 'ui-state-active' : ''}" url="#{url.contact.list}" /> 
	        </p:submenu>
	        <p:submenu label="#{i18n['public.searchDatasets']}">
	            <p:menuitem value="#{i18n['public.search']} #{i18n['common.processes']}" styleClass="#{activeMenu == Constants.MENU_SEARCHPROCESS ? 'ui-state-active' : ''}" rendered="#{feature.searchProcesses}" url="#{url.process.searchForm}" />
	        </p:submenu>
	    </p:menu>
    </h:form>
     
</ui:composition>